WITH A AS (
SELECT
	"WERKS",
	"AT_SSD_SHIPTO_GENERAL_PKUNAG",
	"SPMON",
	sum("PY_SHIPPED_QTY") AS "PY_SHIPPED_QTY",
	sum("PY2_SHIPPED_QTY") AS "PY2_SHIPPED_QTY",
	sum("PY_TRUE_DMD_ORIG_RDD_QTY") AS "PY_TRUE_DMD_QTY"
	
	-- dp/CV_SDP_DMD_PLANNING_DIRECT_QUERY (replace current with)
    FROM "_SYS_BIC"."dp/CV_SPP_DP_DEMAND_PLANNING_DIRECT_QUERY"(
		'PLACEHOLDER' = ('$$ip_yyyymm_from$$','202101'),
		'PLACEHOLDER' = ('$$ip_yyyymm_to$$','202212'),
		'PLACEHOLDER' = ('$$ip_qty_uom$$','PAL'),
		'PLACEHOLDER' = ('$$ip_wgt_uom$$','LB'),
		'PLACEHOLDER' = ('$$ip_cust_grp$$','<Enter Value>')
	 )
	 
	 WHERE "WERKS" IN ('SL07','SL13','SL18','SL19','SL30', 'SL41')
	 AND "AT_SSD_SHIPTO_GENERAL_PKUNAG" IS NOT NULL
	 
	 GROUP BY
	 	"WERKS",
		"AT_SSD_SHIPTO_GENERAL_PKUNAG",
		"SPMON"
	
	ORDER BY
		"WERKS",
		"SPMON",
		"AT_SSD_SHIPTO_GENERAL_PKUNAG"),

B AS (
SELECT
	 "CA_WERKS_NEW",
	 "SHIPTO",
	 "SHIPTO_DESC",
	 "CALMONTH",
	 round(sum("LE_DMD_FCST_CURR"),2) AS "LE_DMD_FCST_CURR",
	 round(sum("CM_DMD_FCST_QTY"),2) AS "CM_DMD_FCST_QTY",
	 round(sum("PLAN_CURR"),2) AS "PLAN_CURR",
	 round(sum("CM_PLAN_QTY"),2) AS "CM_PLAN_QTY",
	 round(sum("CM_TRUE_DMD_QTY"),2) AS "CM_TRUE_DMD_QTY"
	 
	FROM "_SYS_BIC"."sca/CV_SCA_PLANNING_SHIPTO_QUERY"(
		'PLACEHOLDER' = ('$$ip_yyyymm_to$$','202212'),
		'PLACEHOLDER' = ('$$ip_scenario$$','Current_20220113'),
		'PLACEHOLDER' = ('$$ip_number_prev_months$$','6'),
		'PLACEHOLDER' = ('$$ip_qty_uom$$','PAL'),
		'PLACEHOLDER' = ('$$ip_wgt_uom$$','LB'),
		'PLACEHOLDER' = ('$$ip_yyyymm_from$$','202101')
	)
	 
	 WHERE
	 	"CA_WERKS_NEW" IN ('SL07','SL13','SL18','SL19','SL30', 'SL41')
	 	--AND
	 	--"SHIPTO" IN ('0000017941')
	 
	GROUP BY
	 	"CA_WERKS_NEW",
	 	"SHIPTO",
	 	"SHIPTO_DESC",
	 	"CALMONTH"
	 
	ORDER BY
		"SHIPTO",
		"CALMONTH"
	),
	
CAL AS (
	SELECT
		"Calmonth" CALMONTH,
		"Month",
		"Monthwk",
		"Calmonthwk",
		"Calweek" CALWEEK,
		"Days",
		"DaysInMonth",
		"Days"/"DaysInMonth" PMONTH
	FROM "ZFCC_SELF_SERV"."DATE_KEY_MONTOSUN"
	),
	
MM AS (
WITH dt_sap AS (
	SELECT
		"DATE_SAP",
		"CALWEEK",
		"CA_MON_TO_SUN_CALWEEK"
		
	FROM "_SYS_BIC"."md.support.other/CV_AT_TIME_DAY"(
	--'PLACEHOLDER' = 
	--('$$ip_yyyymm_to$$',
	 --'202112'),
	 'PLACEHOLDER' = ('$$ip_yyyymm_from$$',
	 '202101'))
	 
	 ORDER BY
	 "DATE_SAP"
	),

base_data as (
SELECT
	A."DATE_SAP" AS "DATE_SAP",
	A."YEAR" AS "YEAR",
	A."MONTH" AS "MONTH",
	A."CALMONTH" AS "CALMONTH",
	A."CALWEEK" AS "CALWEEK",
	dt_sap."CA_MON_TO_SUN_CALWEEK",
	cast(concat(left(dt_sap."CA_MON_TO_SUN_CALWEEK",4)-1, right(dt_sap."CA_MON_TO_SUN_CALWEEK",2)) AS nvarchar(6)) AS "PY_CALWEEK",
	A."WERKS" AS "WERKS",
	concat(A."CALWEEK",concat(A."WERKS",A."PKUNAG")) AS "CURR_KEY",
	concat(cast(concat(left(dt_sap."CA_MON_TO_SUN_CALWEEK",4)-1, right(dt_sap."CA_MON_TO_SUN_CALWEEK",2)) AS nvarchar(6)),concat(A."WERKS",A."PKUNAG")) AS "PY_KEY",
	A."CA_RECEIPT_ISSUE_IND" AS "CA_RECEIPT_ISSUE_IND",
	A."BWART" AS "MVMNT_TYPE",
	A."BTEXT" AS "MVMNT_TYPE_DESC",
	A."MBLNR" AS "MAT_DOC",
	A."PKUNAG" AS "RECIPIENT_SHIPTO",
	A."PKUNAG_DESC" AS "RECIPIENT_SHIPTO_DESC",
	A."RECV_ISSUE_PLANT" AS "RECV_ISSUE_PLANT",
	A."RECV_ISSUE_PLANT_DESC" AS "RECV_ISSUE_PLANT_DESC",
	A."PO_SUPPLYING_ISSUE_PLANT" AS "PO_SUPPLYING_ISSUE_PLANT",
	A."LIFNR" AS "VENDOR",
	A."NAME1" AS "VENDOR_DESC",
	B."PSTLZ" AS "VENDOR_ZIP",
	B."ORT01" AS "VENDOR_CITY",
	B."REGIO" AS "VENDOR_STATE",
	A."MTART" AS "MATERIAL_TYPE",
	A."SEMI_TYPE" AS "MATERIAL_TYPE_2",
	A."PRODH1_DESC" AS "PRODH1_DESC",
	A."ZPRODH2_DESC" AS "ZPRODH2_DESC",
	A."MVGR1_DESC" AS "MATERIAL_BRAND",
	A."MATNR" AS "MATERIAL_NUM",
	A."MATNR_DESC" AS "MATERIAL_DESC",
	A."CM_MEINS_DISPLAY" AS "BASE_UOM",
	A."CM_QTYUOM_DISP" AS "QTY_UOM",
	A."CM_WGT_UOMDISP" AS "WGT_UOM",
	CASE
		WHEN A."BWART" IN ('541','543','601','641','901','Z41') AND A."CA_RECEIPT_ISSUE_IND" = 'Issue' THEN 'GOODS ISSUE'
		WHEN A."BWART" IN ('101','501','657') AND A."CA_RECEIPT_ISSUE_IND" = 'Receipt' THEN 'GOODS RECEIPT'
		ELSE NULL
	END AS "MVMNT_DIR",
	CASE
		WHEN A."BWART" = '541' THEN A."LIFNR"
		WHEN A."BWART" = '543' THEN A."LIFNR"
		WHEN A."BWART" = '601' THEN A."PKUNAG"
		WHEN A."BWART" = '641' AND A."CA_RECEIPT_ISSUE_IND" = 'Issue' THEN A."PKUNAG"
		WHEN A."BWART" = '901' THEN A."PKUNAG"
		WHEN A."BWART" = 'Z41' THEN A."PKUNAG"
		ELSE NULL
	END AS "RECIPIENT_ID",
	CASE
		WHEN A."BWART" = '541' THEN A."NAME1"
		WHEN A."BWART" = '543' THEN A."NAME1"
		WHEN A."BWART" = '601' THEN A."PKUNAG_DESC"
		WHEN A."BWART" = '641' AND A."CA_RECEIPT_ISSUE_IND" = 'Issue' THEN A."PKUNAG"
		WHEN A."BWART" = '901' THEN A."PKUNAG_DESC"
		WHEN A."BWART" = 'Z41' THEN A."PKUNAG_DESC"
		ELSE NULL
	END AS "RECIPIENT_DESC",
	CASE
		WHEN A."BWART" = '101' AND A."BTEXT" = 'GR goods receipt' THEN A."LIFNR"
		WHEN A."BWART" = '101' AND A."BTEXT" = 'GR stock in transit' THEN A."PO_SUPPLYING_ISSUE_PLANT"
		WHEN A."BWART" = '101' AND A."BTEXT" = 'GR to SC vendor' THEN A."LIFNR"
		WHEN A."BWART" = '501' THEN 'GR W/O PO'
		WHEN A."BWART" = '657' THEN A."PKUNAG"
		ELSE NULL
	END AS "SUPPLIER_ID",
	CASE
		WHEN A."BWART" = '101' AND A."BTEXT" = 'GR goods receipt' THEN A."NAME1"
		WHEN A."BWART" = '101' AND A."BTEXT" = 'GR stock in transit' THEN A."PO_SUPPLYING_ISSUE_PLANT"
		WHEN A."BWART" = '101' AND A."BTEXT" = 'GR to SC vendor' THEN A."NAME1"
		WHEN A."BWART" = '501' THEN 'GR W/O PO'
		WHEN A."BWART" = '657' THEN A."PKUNAG_DESC"
		ELSE NULL
	END AS "SUPPLIER_DESC",
	SUM(A."CM_SMM_MENGE_NET_WGT") AS "MATERIAL_MVMNT_NET_WGT",
	SUM(A."CM_SMM_MENGE_GROSS_WGT") AS "MATERIAL_MVMNT_GROSS_WGT",
	SUM(A."CM_SMM_MENGE_QTY") AS "MATERIAL_MVMNT_QTY",
	SUM(A."CM_MVMT_QTY_WH") AS "MATERIAL_MVMNT_QTY_WMPAL"
	
FROM 
	"_SYS_BIC"."mm/CV_SMM_MATERIAL_MVNT_QUERY"
	('PLACEHOLDER' = ('$$ip_qty_uom$$',
	 'PAL'),
	 'PLACEHOLDER' = ('$$ip_wgt_uom$$',
	 'LB'),
	 'PLACEHOLDER' = ('$$ip_yyyymm_from$$',
	 '202001')
	 --'PLACEHOLDER' = ('$$ip_yyyymm_to$$',
	 --'202112')
	 ) AS A
	 
LEFT OUTER JOIN "PRD_010"."LFA1" AS B
ON A."LIFNR" = B."LIFNR"

LEFT OUTER JOIN dt_sap ON A."DATE_SAP" = dt_sap."DATE_SAP"

WHERE
	A."WERKS" IN ('SL07','SL13','SL18','SL19','SL30','SL41')
AND
	A."CA_RECEIPT_ISSUE_IND" IN ('Issue')
AND
	A."BWART" IN ('541','543','601','641','901','Z41')
AND
	A."MTART" NOT IN ('PACK','WERT')
AND
	dt_sap."CA_MON_TO_SUN_CALWEEK" IS NOT NULL

GROUP BY
	A."DATE_SAP",
	A."YEAR",
	A."MONTH",
	A."CALMONTH",
	A."CALWEEK",
	dt_sap."CA_MON_TO_SUN_CALWEEK",
	A."WERKS",
	A."CA_RECEIPT_ISSUE_IND",
	A."BWART",
	A."BTEXT",
	A."MBLNR",
	A."PKUNAG",
	A."PKUNAG_DESC",
	A."RECV_ISSUE_PLANT",
	A."RECV_ISSUE_PLANT_DESC",
	A."PO_SUPPLYING_ISSUE_PLANT",
	A."LIFNR",
	A."NAME1",
	B."PSTLZ",
	B."ORT01",
	B."REGIO",
	A."MTART",
	A."SEMI_TYPE",
	A."PRODH1_DESC",
	A."ZPRODH2_DESC",
	A."MVGR1_DESC",
	A."MATNR",
	A."MATNR_DESC",
	A."CM_MEINS_DISPLAY",
	A."CM_QTYUOM_DISP",
	A."CM_WGT_UOMDISP"
	)

	SELECT
		base_data."YEAR",
		base_data."MONTH",
		base_data."CALMONTH",
		base_data."CA_MON_TO_SUN_CALWEEK",
		base_data."PY_CALWEEK",
		base_data."CURR_KEY",
		base_data."PY_KEY",
		base_data."WERKS",
		base_data."CA_RECEIPT_ISSUE_IND",
		base_data."MVMNT_TYPE",
		base_data."MVMNT_TYPE_DESC",
		base_data."RECIPIENT_SHIPTO",
		base_data."RECIPIENT_SHIPTO_DESC",
		base_data."RECV_ISSUE_PLANT",
		base_data."RECV_ISSUE_PLANT_DESC",
		base_data."BASE_UOM" AS "CM_MEINS_DISPLAY",
    	base_data."QTY_UOM",
		base_data."WGT_UOM",
		ROUND(ABS(SUM(base_data."MATERIAL_MVMNT_QTY")),2) AS "MM_QTY"
	
	FROM base_data

	GROUP BY
		base_data."YEAR",
		base_data."MONTH",
		base_data."CALMONTH",
		base_data."CA_MON_TO_SUN_CALWEEK",
		base_data."PY_CALWEEK",
		base_data."CURR_KEY",
		base_data."PY_KEY",
		base_data."WERKS",
		base_data."CA_RECEIPT_ISSUE_IND",
		base_data."MVMNT_TYPE",
		base_data."MVMNT_TYPE_DESC",
		base_data."RECIPIENT_SHIPTO",
		base_data."RECIPIENT_SHIPTO_DESC",
		base_data."RECV_ISSUE_PLANT",
		base_data."RECV_ISSUE_PLANT_DESC",
		base_data."BASE_UOM",
    	base_data."QTY_UOM",
		base_data."WGT_UOM"
	
	ORDER BY
		base_data."WERKS",
		base_data."CA_MON_TO_SUN_CALWEEK",
		base_data."CA_RECEIPT_ISSUE_IND"
		),
		
C AS (
SELECT
	B."CA_WERKS_NEW",
	B."SHIPTO",
	B."SHIPTO_DESC",
	B."CALMONTH",
	cast(concat(left(B."CALMONTH",4)-1, right(B."CALMONTH",2)) AS nvarchar(6)) AS "PY_CALMONTH",
	CAL."CALWEEK",
	MM."CA_MON_TO_SUN_CALWEEK",
	cast(concat(left(CAL."CALWEEK",4)-1, right(CAL."CALWEEK",2)) AS nvarchar(6)) AS "PY_CALWEEK",
	CAL."PMONTH",
	round(sum(B."CM_DMD_FCST_QTY"),2) AS "CM_DMD_FCST_QTY",
	round(sum(B."CM_DMD_FCST_QTY")*CAL.PMONTH,2) AS "P_CM_DMD_FCST_QTY",
	round(sum(A."PY_TRUE_DMD_QTY"),2) AS "PY_TRUE_DMD_QTY",
	round(sum(A."PY_TRUE_DMD_QTY")*CAL.PMONTH,2) AS "P_PY_TRUE_DMD_QTY",
	round(sum(B."CM_PLAN_QTY"),2) AS "CM_PLAN_QTY",
	round(sum(B."CM_PLAN_QTY")*CAL.PMONTH,2) AS "P_CM_PLAN_QTY",
	round(sum(MM."MM_QTY"),2) AS "MM_QTY"
	
	FROM B
	LEFT OUTER JOIN A ON B."SHIPTO" = A."AT_SSD_SHIPTO_GENERAL_PKUNAG"
		AND B."CALMONTH" = A."SPMON"
		AND B."CA_WERKS_NEW" = A."WERKS"
		
	LEFT JOIN CAL
	ON CAL.CALMONTH = B.CALMONTH
	
	LEFT OUTER JOIN MM ON B."SHIPTO" = MM."RECIPIENT_SHIPTO"
		AND B."CA_WERKS_NEW" = MM."WERKS"
		AND B."CALMONTH" = MM."CALMONTH"
		AND CAL.CALWEEK = MM."CA_MON_TO_SUN_CALWEEK"
	
	GROUP BY
		B."CA_WERKS_NEW",
		B."SHIPTO",
		B."SHIPTO_DESC",
		B."CALMONTH",
		CAL.CALWEEK,
		MM."CA_MON_TO_SUN_CALWEEK",
		MM."PY_CALWEEK",
		CAL.PMONTH
	
	ORDER BY
		B."CA_WERKS_NEW",
		B."SHIPTO",
		B."CALMONTH",
		CAL.CALWEEK
		),
		
CM AS (
	SELECT
		"KUNNR",
		"NAME1",
		"ORT01" AS "CST_CITY",
		"REGIO" AS "CST_STATE",
		"PSTLZ" AS "CST_ZIP",
		"LAND1" AS "CST_COUNTRY"
	
	FROM "PRD_010"."KNA1"
	),
	
DCM AS (
	SELECT
		"WERKS",
		"NAME1" AS "DC_NAME",
		"ORT01" AS "DC_CITY",
		"REGIO" AS "DC_STATE",
		"PSTLZ" AS "DC_ZIP"
		
	FROM "PRD_010"."T001W"
	),

SOLDTOMM AS (
	WITH custgrp AS (
	SELECT
		"SOLDTO",
		"SOLDTO_DESC",
		"CUST_GRP_RPT",
		"CUST_GRP_DESC",
		"CA_KEY_CUST_GRP_DESC",
		"SHIPTO",
		"SHIPTO_DESC"

		FROM "_SYS_BIC"."md/CV_SMD_SOLDTO_MASTER_QUERY"
		
		WHERE "SHIPTO" IS NOT NULL
		AND "CUST_GRP_RPT" <> 'Inactive'
	
		ORDER BY "SHIPTO"),

	counts AS (
	SELECT
		"SHIPTO",
		COUNT("SOLDTO"),
		COUNT("CUST_GRP_RPT"),
		COUNT("CA_KEY_CUST_GRP_DESC"),
		COUNT("SOLDTO")+COUNT("CUST_GRP_RPT")+COUNT("CA_KEY_CUST_GRP_DESC") AS "Total"
	
		FROM custgrp
	
	GROUP BY
		"SHIPTO"
		
	ORDER BY
		COUNT("SOLDTO")+COUNT("CUST_GRP_RPT")+COUNT("CA_KEY_CUST_GRP_DESC") DESC)
		
	SELECT
		custgrp."SOLDTO",
		custgrp."SOLDTO_DESC",
		custgrp."CUST_GRP_RPT",
		custgrp."CUST_GRP_DESC",
		custgrp."CA_KEY_CUST_GRP_DESC",
		custgrp."SHIPTO",
		custgrp."SHIPTO_DESC",
		SUM(counts."Total")
	
		FROM custgrp
		LEFT OUTER JOIN counts ON custgrp."SHIPTO" = counts."SHIPTO"
	
		WHERE counts."Total" < 4
	
	GROUP BY
		custgrp."SOLDTO",
		custgrp."SOLDTO_DESC",
		custgrp."CUST_GRP_RPT",
		custgrp."CUST_GRP_DESC",
		custgrp."CA_KEY_CUST_GRP_DESC",
		custgrp."SHIPTO",
		custgrp."SHIPTO_DESC"
		
	ORDER BY
		SUM(counts."Total") DESC
		)
		
SELECT
	C."CA_WERKS_NEW",
	DCM."DC_NAME",
	DCM."DC_CITY",
	DCM."DC_STATE",
	DCM."DC_ZIP",
	SOLDTOMM."CUST_GRP_RPT",
	SOLDTOMM."SOLDTO_DESC",
	C."SHIPTO",
	C."SHIPTO_DESC",
	CM."CST_CITY",
	CM."CST_ZIP",
	CM."CST_STATE",
	CM."CST_COUNTRY",
	C."CALMONTH",
	C."PY_CALMONTH",
	C."CALWEEK",
	C."PY_CALWEEK",
	C."PMONTH",
	SUM(C."CM_DMD_FCST_QTY") AS "CM_DMD_FCST_QTY",
	SUM(C."P_CM_DMD_FCST_QTY") AS "P_CM_DMD_FCST_QTY",
	SUM(C."PY_TRUE_DMD_QTY") AS "PY_TRUE_DMD_QTY",
	SUM(C."P_PY_TRUE_DMD_QTY") AS "P_PY_TRUE_DMD_QTY",
	SUM(C."CM_PLAN_QTY") AS "CM_PLAN_QTY",
	SUM(C."P_CM_PLAN_QTY") AS "P_CM_PLAN_QTY",
	SUM(C."MM_QTY") AS "CURR_MM_QTY",
	SUM(MM."MM_QTY") AS "PY_MM_QTY"
	
	FROM C
	LEFT OUTER JOIN MM ON C."SHIPTO" = MM."RECIPIENT_SHIPTO"
		AND C."CA_WERKS_NEW" = MM."WERKS"
		AND C."PY_CALMONTH" = MM."CALMONTH"
		AND C."PY_CALWEEK" = MM."CA_MON_TO_SUN_CALWEEK"
		
	LEFT OUTER JOIN CM ON C."SHIPTO" = CM."KUNNR"
	LEFT OUTER JOIN DCM ON C."CA_WERKS_NEW" = DCM."WERKS"
	LEFT OUTER JOIN SOLDTOMM ON C."SHIPTO" = SOLDTOMM."SHIPTO"
	
	--WHERE C."SHIPTO" IN ('0000019062')
	--AND C."CA_WERKS_NEW" IN ('SL18')

	--WHERE C."CALWEEK" > 202205
	
	GROUP BY
		C."CA_WERKS_NEW",
		DCM."DC_NAME",
		DCM."DC_CITY",
		DCM."DC_STATE",
		DCM."DC_ZIP",
		SOLDTOMM."CUST_GRP_RPT",
		SOLDTOMM."SOLDTO_DESC",	
		C."SHIPTO",
		C."SHIPTO_DESC",
		CM."CST_CITY",
		CM."CST_ZIP",
		CM."CST_STATE",
		CM."CST_COUNTRY",
		C."CALMONTH",
		C."PY_CALMONTH",
		C."CALWEEK",
		C."PY_CALWEEK",
		C."PMONTH"
		
	ORDER BY
		C."CA_WERKS_NEW",
		C."CALMONTH",
		C."CALWEEK",
		C."SHIPTO"